name: radio_online_app
description: "Um aplicativo de rádio online desenvolvido com Flutter."

# Previne a publicação acidental em pub.dev.
publish_to: 'none' 

# A versão da aplicação. O primeiro número é a versão e o que vem depois do + é o número da compilação (build).
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Define a versão compatível do Dart.

dependencies:
  flutter:
    sdk: flutter

  # Pacote para funcionalidades de áudio, como tocar streams de rádio.
  audioplayers: ^6.0.0

  # Pacote padrão para ícones do estilo iOS.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Pacote que ajuda a manter o código limpo e com boas práticas.
  flutter_lints: ^3.0.0

# A secção seguinte é específica para a configuração do Flutter.
flutter:
  
  # A linha seguinte garante que estás a usar o Material Design.
  # Essencial para o visual Material 3 / Material You que queres.
  uses-material-design: true

  # Para adicionar recursos como imagens, podes descomentar esta secção:
  # assets:
  #   - assets/images/
  
  # Para adicionar fontes personalizadas, podes descomentar esta secção:
  # fonts:
  #   - family: MinhaFonte
  #     fonts:
  #       - asset: assets/fonts/MinhaFonte-Regular.ttf
  #       - asset: assets/fonts/MinhaFonte-Bold.ttf
  #         weight: 700
